[package]
name = "restop_lib"
version = "0.1.0"
authors = ["DeltaManiac <maxpaynered@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postman_collection = "0.1.0"
anyhow = "1.0.43"
thiserror = "1.0.26"